const API_BASE_URL = 'http://localhost:8080';
const KAKAO_CALLBACK_URL = process.env.NEXT_PUBLIC_KAKAO_CALLBACK_URL || '/';
const KAKAO_MAP_APIKEY = 'KakaoAK 39e2904a8ec248d9db91d79d53358ab1';

export { API_BASE_URL, KAKAO_CALLBACK_URL, KAKAO_MAP_APIKEY };
